#!/bin/bash

export ENVIRONMENT_VERSION=1

## (C) 2023
## Ramon Brooker <rbrooker@aeo3.io>

# shellcheck source=/dev/null

##########################         VARIABLES          ########################

## History Settings
shopt -s histappend
export PROMPT_COMMAND='history -a'
export HISTIGNORE="x:exit:clean:su:pwd:clear:ls:ll: "
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth:erasedups
export HISTTIMEFORMAT="%Y %h %d %H:%M:%S  "

export LIBGL_ALWAYS_INDIRECT=1

if [[ -x /usr/bin/nvim ]]; then
    export EDITOR=/usr/bin/nvim
fi
##########################         EXPORTS          ########################

if [[ ${UID} -gt 999 ]]; then
    PATH=${HOME}/.bin
    export PATH=${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/bin
else
    # Root or System User
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
fi

if [[ -x /usr/bin/snap ]]; then
    export PATH=${PATH}:/snap/bin
fi

