---
# Cognitify Installation Playbook
# (c) 2026 Ramon Brooker <rbrooker@aeo3.io>
#
# This playbook installs cognitify shell customisations on target systems.
#
# Usage:
#   ansible-playbook -i inventory install.yml
#   ansible-playbook -i inventory install.yml -e "install_user=myuser" -e "skip_packages=true"
#
# Variables:
#   install_user: User to install dotfiles for (default: ansible_user)
#   skip_packages: Skip package installation (default: false)
#   docker_mode: Use Docker/container mode (default: false)
#   hostname_colour: Set default hostname colour (optional)

- name: Install Cognitify
  hosts: all
  become: yes
  vars:
    cognitify_version: "{{ lookup('file', 'version') | default('0.0.1', true) | trim }}"
    install_user: "{{ ansible_user | default('root') }}"
    skip_packages: false
    docker_mode: false
    hostname_colour: ""
    group_name: "cognitify"
    config_dest: "/etc/bash.bashrc.d"
    prompts_dest: "/etc/prompts"
    completions_dest: "/etc/bash_completion.d"
    profile_d_dest: "/etc/profile.d"
    skel_dest: "/etc/skel"
    prefix: "/usr/local"
    src_dir: "{{ playbook_dir }}/src"
    config_src: "{{ src_dir }}/bash.bashrc.d"
    prompts_src: "{{ src_dir }}/prompts"
    home_files_src: "{{ src_dir }}/home-files"
    completions_src: "{{ src_dir }}/completions"
    packages_dir: "{{ src_dir }}/packages"
    bin_src: "{{ src_dir }}/usr/local/bin"
    profile_d_src: "{{ src_dir }}/profile.d"
    distro_files_src: "{{ src_dir }}/distro-files"

  tasks:
    - name: Detect package manager
      set_fact:
        pkg_manager: "{{ 'dnf' if ansible_pkg_mgr == 'dnf' else ('yum' if ansible_pkg_mgr == 'yum' else 'unknown') }}"

    - name: Fail if package manager is unknown
      fail:
        msg: "Unsupported package manager. Only yum/dnf are supported."
      when:
        - pkg_manager == "unknown"
        - not skip_packages | bool

    - name: Parse GENERAL packages file
      shell: |
        awk 'NF && $1 !~ /^#/ { 
          for (i = 1; i <= NF; ++i) {
            if ($i !~ /^#/) {
              print $i
            }
          }
        }' "{{ packages_dir }}/GENERAL"
      register: general_packages_output
      changed_when: false
      when: not skip_packages | bool

    - name: Set GENERAL packages fact
      set_fact:
        general_packages: "{{ general_packages_output.stdout_lines | select('length') | list }}"
      when: not skip_packages | bool

    - name: Parse YUM packages file
      shell: |
        awk 'NF && $1 !~ /^#/ { 
          for (i = 1; i <= NF; ++i) {
            if ($i !~ /^#/) {
              print $i
            }
          }
        }' "{{ packages_dir }}/PACKAGES_YUM"
      register: yum_packages_output
      changed_when: false
      when:
        - not skip_packages | bool
        - pkg_manager in ['yum', 'dnf']

    - name: Set YUM packages fact
      set_fact:
        yum_packages: "{{ yum_packages_output.stdout_lines | select('length') | list }}"
      when:
        - not skip_packages | bool
        - pkg_manager in ['yum', 'dnf']

    - name: Combine packages list
      set_fact:
        packages_to_install: "{{ (general_packages | default([])) + (yum_packages | default([])) | unique | list }}"
      when: not skip_packages | bool

    - name: Install packages
      package:
        name: "{{ packages_to_install }}"
        state: present
      when:
        - not skip_packages | bool
        - packages_to_install | length > 0
      ignore_errors: yes

    - name: Create cognitify group
      group:
        name: "{{ group_name }}"
        state: present

    - name: Get user home directory
      shell: getent passwd "{{ install_user }}" | cut -d: -f6
      register: user_home_output
      changed_when: false
      failed_when: false

    - name: Set user home directory fact
      set_fact:
        user_home: "{{ user_home_output.stdout }}"
      when: user_home_output.stdout | length > 0

    - name: Ensure user exists
      fail:
        msg: "User {{ install_user }} does not exist"
      when: user_home is not defined or user_home == ""

    - name: Add user to cognitify group
      user:
        name: "{{ install_user }}"
        groups: "{{ group_name }}"
        append: yes

    - name: Create configuration directory
      file:
        path: "{{ config_dest }}"
        state: directory
        owner: root
        group: "{{ group_name }}"
        mode: '0775'

    - name: Install bash configuration files
      copy:
        src: "{{ config_src }}/"
        dest: "{{ config_dest }}/"
        owner: root
        group: "{{ group_name }}"
        mode: '0775'
        directory_mode: '0775'

    - name: Create version file in config directory
      copy:
        content: "{{ cognitify_version }}\n"
        dest: "{{ config_dest }}/.cognitify-version"
        owner: root
        group: "{{ group_name }}"
        mode: '0644'

    - name: Check if prompts source directory exists
      stat:
        path: "{{ prompts_src }}"
      register: prompts_src_stat

    - name: Create prompts directory
      file:
        path: "{{ prompts_dest }}"
        state: directory
        owner: root
        group: "{{ group_name }}"
        mode: '0775'
      when: prompts_src_stat.stat.exists

    - name: Find prompt files
      find:
        paths: "{{ prompts_src }}"
        file_type: file
        excludes: "lib"
      register: prompt_files
      when: prompts_src_stat.stat.exists

    - name: Install prompt files
      copy:
        src: "{{ item.path }}"
        dest: "{{ prompts_dest }}/{{ item.path | basename }}"
        owner: root
        group: "{{ group_name }}"
        mode: '0644'
      loop: "{{ prompt_files.files | default([]) }}"
      when:
        - prompts_src_stat.stat.exists
        - prompt_files.files | length > 0

    - name: Check if prompts lib directory exists
      stat:
        path: "{{ prompts_src }}/lib"
      register: prompts_lib_stat
      when: prompts_src_stat.stat.exists

    - name: Find prompt library files
      find:
        paths: "{{ prompts_src }}/lib"
        file_type: file
      register: prompt_lib_files
      when:
        - prompts_src_stat.stat.exists
        - prompts_lib_stat.stat.exists is defined
        - prompts_lib_stat.stat.exists

    - name: Create prompts lib directory
      file:
        path: "{{ prompts_dest }}/lib"
        state: directory
        owner: root
        group: "{{ group_name }}"
        mode: '0775'
      when:
        - prompts_src_stat.stat.exists
        - prompts_lib_stat.stat.exists is defined
        - prompts_lib_stat.stat.exists
        - prompt_lib_files.files | length > 0

    - name: Install prompt library files
      copy:
        src: "{{ item.path }}"
        dest: "{{ prompts_dest }}/lib/{{ item.path | basename }}"
        owner: root
        group: "{{ group_name }}"
        mode: '0775'
      loop: "{{ prompt_lib_files.files | default([]) }}"
      when:
        - prompts_src_stat.stat.exists
        - prompts_lib_stat.stat.exists is defined
        - prompts_lib_stat.stat.exists
        - prompt_lib_files.files | length > 0

    - name: Create prompt configuration with hostname colour
      copy:
        content: |
          # Cognitify prompt configuration
          # Generated during installation
          # (c) 2026 Ramon Brooker <rbrooker@aeo3.io>

          # Source colour definitions first
          if [[ -f "{{ prompts_dest }}/lib/cognitifyColours" ]]; then
              source "{{ prompts_dest }}/lib/cognitifyColours"
          fi

          # Set default hostname colour
          export OVERRIDE_HOSTNAME_COLOUR=${ {{ hostname_colour }} }
        dest: "{{ prompts_dest }}/config"
        owner: root
        group: "{{ group_name }}"
        mode: '0644'
      when:
        - hostname_colour | length > 0
        - prompts_src_stat.stat.exists

    - name: Create version file in prompts directory
      copy:
        content: "{{ cognitify_version }}\n"
        dest: "{{ prompts_dest }}/.cognitify-version"
        owner: root
        group: "{{ group_name }}"
        mode: '0644'
      when: prompts_src_stat.stat.exists

    - name: Check if completions source directory exists
      stat:
        path: "{{ completions_src }}"
      register: completions_src_stat

    - name: Create completions directory
      file:
        path: "{{ completions_dest }}"
        state: directory
        mode: '0755'
      when: completions_src_stat.stat.exists

    - name: Find completion files
      find:
        paths: "{{ completions_src }}"
        file_type: file
      register: completion_files
      when: completions_src_stat.stat.exists

    - name: Install shell completions
      copy:
        src: "{{ item.path }}"
        dest: "{{ completions_dest }}/{{ item.path | basename }}"
        mode: '0644'
      loop: "{{ completion_files.files | default([]) }}"
      when:
        - completions_src_stat.stat.exists
        - completion_files.files | length > 0

    - name: Check if home files source directory exists
      stat:
        path: "{{ home_files_src }}"
      register: home_files_src_stat

    - name: Find home files
      find:
        paths: "{{ home_files_src }}"
        file_type: file
      register: home_files
      when: home_files_src_stat.stat.exists

    - name: Backup existing dotfiles
      copy:
        src: "{{ user_home }}/.{{ item.path | basename }}"
        dest: "{{ user_home }}/.{{ item.path | basename }}.orig"
        remote_src: yes
      loop: "{{ home_files.files | default([]) }}"
      when:
        - home_files_src_stat.stat.exists
        - home_files.files | length > 0
      ignore_errors: yes
      failed_when: false

    - name: Install user dotfiles
      copy:
        src: "{{ item.path }}"
        dest: "{{ user_home }}/.{{ item.path | basename }}"
        owner: "{{ install_user }}"
        group: "{{ install_user }}"
        mode: preserve
      loop: "{{ home_files.files | default([]) }}"
      when:
        - home_files_src_stat.stat.exists
        - home_files.files | length > 0

    - name: Check if bin source directory exists
      stat:
        path: "{{ bin_src }}"
      register: bin_src_stat

    - name: Create bin directory
      file:
        path: "{{ prefix }}/bin"
        state: directory
        mode: '0755'
      when: bin_src_stat.stat.exists

    - name: Find binary files
      find:
        paths: "{{ bin_src }}"
        file_type: file
      register: binary_files
      when: bin_src_stat.stat.exists

    - name: Install user binaries
      copy:
        src: "{{ item.path }}"
        dest: "{{ prefix }}/bin/{{ item.path | basename }}"
        mode: '0755'
      loop: "{{ binary_files.files | default([]) }}"
      when:
        - bin_src_stat.stat.exists
        - binary_files.files | length > 0

    - name: Check if docs directory exists
      stat:
        path: "{{ playbook_dir }}/docs"
      register: docs_dir_stat

    - name: Create documentation directory
      file:
        path: "{{ prefix }}/share/doc/cognitify"
        state: directory
        mode: '0755'
      when: docs_dir_stat.stat.exists

    - name: Install documentation
      copy:
        src: "{{ playbook_dir }}/docs/"
        dest: "{{ prefix }}/share/doc/cognitify/"
        mode: preserve
      when: docs_dir_stat.stat.exists

    - name: Check if man page exists
      stat:
        path: "{{ playbook_dir }}/man/man1/cognitify.1"
      register: man_page_stat

    - name: Create man page directory
      file:
        path: "{{ prefix }}/share/man/man1"
        state: directory
        mode: '0755'
      when: man_page_stat.stat.exists

    - name: Install man page
      copy:
        src: "{{ playbook_dir }}/man/man1/cognitify.1"
        dest: "{{ prefix }}/share/man/man1/cognitify.1"
        mode: '0644'
      when: man_page_stat.stat.exists

    - name: Update man database
      command: mandb -q
      ignore_errors: yes
      when: man_page_stat.stat.exists

    - name: Create profile.d directory
      file:
        path: "{{ profile_d_dest }}"
        state: directory
        mode: '0755'
      when: profile_d_src | length > 0

    - name: Check if profile.d source directory exists
      stat:
        path: "{{ profile_d_src }}"
      register: profile_d_src_stat

    - name: Find profile.d files
      find:
        paths: "{{ profile_d_src }}"
        file_type: file
      register: profile_d_files
      when: profile_d_src_stat.stat.exists

    - name: Install profile.d snippets
      copy:
        src: "{{ item.path }}"
        dest: "{{ profile_d_dest }}/{{ item.path | basename }}"
        mode: '0644'
      loop: "{{ profile_d_files.files | default([]) }}"
      when:
        - profile_d_src_stat.stat.exists
        - profile_d_files.files | length > 0

    - name: Create skel directory
      file:
        path: "{{ skel_dest }}"
        state: directory
        mode: '0755'
      when: home_files_src_stat.stat.exists

    - name: Install dotfiles to /etc/skel
      copy:
        src: "{{ item.path }}"
        dest: "{{ skel_dest }}/.{{ item.path | basename }}"
        mode: '0644'
      loop: "{{ home_files.files | default([]) }}"
      when:
        - home_files_src_stat.stat.exists
        - home_files.files | length > 0

    - name: Check if distro files source directory exists
      stat:
        path: "{{ distro_files_src }}"
      register: distro_files_src_stat

    - name: Check if zypper.sh exists
      stat:
        path: "{{ distro_files_src }}/zypper.sh"
      register: zypper_sh_stat
      when: distro_files_src_stat.stat.exists

    - name: Install distro-specific files
      copy:
        src: "{{ distro_files_src }}/zypper.sh"
        dest: "{{ completions_dest }}/zypper"
        mode: '0644'
      when:
        - pkg_manager == 'zypper'
        - distro_files_src_stat.stat.exists
        - zypper_sh_stat.stat.exists

    - name: Installation complete
      debug:
        msg:
          - "Cognitify version {{ cognitify_version }} installed successfully!"
          - "Installed for user: {{ install_user }}"
          - "Please log out and log back in for changes to take effect"
