# Cognitify Makefile
# (C) 2024 Ramon Brooker <rbrooker@aeo3.io>

# Include configuration generated by configure script
-include config.mk

# Default target
.DEFAULT_GOAL := help

# Check if config.mk exists
ifeq ($(wildcard config.mk),)
$(error config.mk not found. Please run ./configure first)
endif

# Variables with defaults (if not set by config.mk)
PREFIX ?= /usr/local
ETC_DIR ?= /etc
CONFIG_DEST ?= $(ETC_DIR)/bash.bashrc.d
COMPLETIONS_DEST ?= $(ETC_DIR)/bash_completion.d
SRC_DIR ?= src
CONFIG_SRC ?= $(SRC_DIR)/bash.bashrc.d
HOME_FILES_SRC ?= $(SRC_DIR)/home-files
COMPLETIONS_SRC ?= $(SRC_DIR)/completions
PACKAGES_DIR ?= $(SRC_DIR)/packages
BIN_SRC ?= $(SRC_DIR)/usr/local/bin
DISTRO_FILES_SRC ?= $(SRC_DIR)/distro-files
INSTALL_USER ?= $(shell whoami)
GROUP_NAME ?= cognitify
VERSION ?= 0.0.1

# Colours for output
RED := \033[0;31m
GREEN := \033[0;32m
YELLOW := \033[0;33m
NC := \033[0m # No Colour

.PHONY: help all install install-config install-completions install-home install-bin install-distro post-install clean uninstall check-root

help: ## Show this help message
	@echo "Cognitify Build System"
	@echo ""
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*?## "}; /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-20s$(NC) %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@echo ""
	@echo "Configuration (from config.mk):"
	@echo "  Distribution: $(DISTRO_ID)"
	@echo "  Package Manager: $(PKG_MANAGER)"
	@echo "  Prefix: $(PREFIX)"
	@echo "  Config Dest: $(CONFIG_DEST)"
	@echo "  Install User: $(INSTALL_USER)"

all: ## Build the project (currently just validates)
	@echo "$(GREEN)[cognitify]$(NC) Building..."
	@if [ ! -d "$(SRC_DIR)" ]; then \
		echo "$(RED)Error: Source directory not found: $(SRC_DIR)$(NC)" >&2; \
		exit 1; \
	fi
	@if [ ! -f "version" ]; then \
		echo "$(YELLOW)Warning: version file not found$(NC)" >&2; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Build validation complete"

check-root: ## Check if running as root (for install targets)
	@if [ "$$(id -u)" -ne 0 ]; then \
		echo "$(RED)Error: This target requires root privileges. Use: sudo make install$(NC)" >&2; \
		exit 1; \
	fi

install: check-root all install-config install-completions install-home install-bin install-distro post-install ## Install all components
	@echo ""
	@echo "$(GREEN)[cognitify]$(NC) Installation completed successfully!"
	@echo "$(GREEN)[cognitify]$(NC) Version $(VERSION) installed"
	@echo "$(GREEN)[cognitify]$(NC) Please log out and log back in for changes to take effect"

install-config: check-root ## Install bash configuration files
	@echo "$(GREEN)[cognitify]$(NC) Installing configuration files..."
	@if [ ! -d "$(CONFIG_SRC)" ]; then \
		echo "$(RED)Error: Configuration source not found: $(CONFIG_SRC)$(NC)" >&2; \
		exit 1; \
	fi
	@install -d -m 775 -o root -g "$(GROUP_NAME)" "$(CONFIG_DEST)" || \
		(if ! getent group "$(GROUP_NAME)" >/dev/null 2>&1; then \
			echo "$(GREEN)[cognitify]$(NC) Creating group $(GROUP_NAME)..."; \
			groupadd "$(GROUP_NAME)"; \
		fi; \
		install -d -m 775 -o root -g "$(GROUP_NAME)" "$(CONFIG_DEST)")
	@cp -R "$(CONFIG_SRC)/." "$(CONFIG_DEST)/"
	@chown -R root:"$(GROUP_NAME)" "$(CONFIG_DEST)"
	@chmod -R 775 "$(CONFIG_DEST)"
	@echo "$(CONFIG_DEST)/.cognitify-version" | xargs -I {} sh -c 'echo "$(VERSION)" > {}'
	@chmod 644 "$(CONFIG_DEST)/.cognitify-version"
	@echo "$(GREEN)[cognitify]$(NC) Configuration installed to $(CONFIG_DEST)"

install-completions: check-root ## Install shell completions
	@echo "$(GREEN)[cognitify]$(NC) Installing shell completions..."
	@if [ ! -d "$(COMPLETIONS_SRC)" ]; then \
		echo "$(YELLOW)Warning: Completions source not found: $(COMPLETIONS_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(COMPLETIONS_DEST)"
	@find "$(COMPLETIONS_SRC)" -maxdepth 1 -type f -print0 | \
		while IFS= read -r -d '' file; do \
			install -m 644 "$$file" "$(COMPLETIONS_DEST)/"; \
		done
	@echo "$(GREEN)[cognitify]$(NC) Completions installed to $(COMPLETIONS_DEST)"

install-home: check-root ## Install user dotfiles
	@echo "$(GREEN)[cognitify]$(NC) Installing home directory files..."
	@HOME_DIR=$$(getent passwd "$(INSTALL_USER)" | cut -d: -f6); \
	if [ -z "$$HOME_DIR" ] || [ ! -d "$$HOME_DIR" ]; then \
		echo "$(RED)Error: Unable to resolve home directory for user $(INSTALL_USER)$(NC)" >&2; \
		exit 1; \
	fi; \
	if [ ! -d "$(HOME_FILES_SRC)" ]; then \
		echo "$(YELLOW)Warning: Home files source not found: $(HOME_FILES_SRC)$(NC)" >&2; \
		exit 0; \
	fi; \
	for file in "$(HOME_FILES_SRC)"/*; do \
		[ -f "$$file" ] || continue; \
		base=".$$(basename "$$file")"; \
		dest="$$HOME_DIR/$$base"; \
		if [ -e "$$dest" ] && [ ! -e "$$dest.orig" ]; then \
			cp "$$dest" "$$dest.orig"; \
			echo "$(GREEN)[cognitify]$(NC) Backed up existing $$base to $$base.orig"; \
		fi; \
		cp "$$file" "$$dest"; \
		chown "$(INSTALL_USER):$(INSTALL_USER)" "$$dest"; \
	done; \
	echo "$(GREEN)[cognitify]$(NC) Home files installed to $$HOME_DIR"

install-bin: check-root ## Install user binaries
	@echo "$(GREEN)[cognitify]$(NC) Installing user binaries..."
	@if [ ! -d "$(BIN_SRC)" ]; then \
		echo "$(YELLOW)Warning: Binaries source not found: $(BIN_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(PREFIX)/bin"
	@find "$(BIN_SRC)" -type f -executable -print0 | \
		while IFS= read -r -d '' file; do \
			install -m 755 "$$file" "$(PREFIX)/bin/"; \
		done
	@echo "$(GREEN)[cognitify]$(NC) Binaries installed to $(PREFIX)/bin"

install-distro: check-root ## Install distro-specific files
	@echo "$(GREEN)[cognitify]$(NC) Installing distro-specific files..."
	@if [ ! -d "$(DISTRO_FILES_SRC)" ]; then \
		echo "$(YELLOW)Warning: Distro files source not found: $(DISTRO_FILES_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@case "$(PKG_MANAGER)" in \
		zypper) \
			if [ -f "$(DISTRO_FILES_SRC)/zypper.sh" ]; then \
				install -m 644 "$(DISTRO_FILES_SRC)/zypper.sh" "$(COMPLETIONS_DEST)/zypper" || true; \
				echo "$(GREEN)[cognitify]$(NC) Installed zypper completion"; \
			fi \
			;; \
	esac

post-install: check-root ## Run post-installation script (package installation)
	@if [ "$(SKIP_PACKAGES)" = "yes" ]; then \
		echo "$(GREEN)[cognitify]$(NC) Skipping package installation (SKIP_PACKAGES=yes)"; \
		exit 0; \
	fi
	@if [ "$(PKG_MANAGER)" = "unknown" ] || [ -z "$(PKG_MANAGER)" ]; then \
		echo "$(YELLOW)Warning: No supported package manager detected. Skipping package installation.$(NC)" >&2; \
		exit 0; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Running post-installation package script..."
	@./post-install.sh "$(PKG_MANAGER)" "$(PKG_MANAGER_INSTALL)" "$(PKG_MANAGER_UPDATE)" "$(PACKAGES_DIR)" "$(INCLUDE_GUI)"

clean: ## Clean build artifacts
	@echo "$(GREEN)[cognitify]$(NC) Cleaning..."
	@rm -f config.mk
	@echo "$(GREEN)[cognitify]$(NC) Clean complete"

uninstall: check-root ## Uninstall cognitify (removes files but keeps backups)
	@echo "$(RED)[cognitify]$(NC) Uninstalling..."
	@echo "$(YELLOW)Warning: This will remove installed files but keep backups with .orig suffix$(NC)"
	@read -p "Continue? [y/N] " -n 1 -r; \
	echo; \
	if [[ ! $$REPLY =~ ^[Yy]$$ ]]; then \
		echo "Cancelled."; \
		exit 0; \
	fi
	@rm -rf "$(CONFIG_DEST)"
	@rm -rf "$(COMPLETIONS_DEST)"/*cognitify* 2>/dev/null || true
	@HOME_DIR=$$(getent passwd "$(INSTALL_USER)" | cut -d: -f6); \
	if [ -n "$$HOME_DIR" ] && [ -d "$$HOME_DIR" ]; then \
		for file in "$(HOME_FILES_SRC)"/*; do \
			[ -f "$$file" ] || continue; \
			base=".$$(basename "$$file")"; \
			dest="$$HOME_DIR/$$base"; \
			if [ -e "$$dest" ]; then \
				rm -f "$$dest"; \
				if [ -e "$$dest.orig" ]; then \
					mv "$$dest.orig" "$$dest"; \
					echo "$(GREEN)[cognitify]$(NC) Restored $$base from backup"; \
				fi; \
			fi; \
		done; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Uninstall complete"

