# Cognitify Makefile
# (c) 2026 Ramon Brooker <rbrooker@aeo3.io>

# Include configuration generated by configure script
-include config.mk

# Default target
.DEFAULT_GOAL := help

# Check if config.mk exists
ifeq ($(wildcard config.mk),)
$(error config.mk not found. Please run ./configure first)
endif

# Variables with defaults (if not set by config.mk)
PREFIX ?= /usr/local
ETC_DIR ?= /etc
CONFIG_DEST ?= $(ETC_DIR)/bash.bashrc.d
COMPLETIONS_DEST ?= $(ETC_DIR)/bash_completion.d
SRC_DIR ?= src
CONFIG_SRC ?= $(SRC_DIR)/bash.bashrc.d
PROMPTS_SRC ?= $(SRC_DIR)/prompts
PROMPTS_DEST ?= $(ETC_DIR)/prompts
HOME_FILES_SRC ?= $(SRC_DIR)/home-files
HOME_FILES_EXTENDED_SRC ?= $(SRC_DIR)/home-files-extended
COMPLETIONS_SRC ?= $(SRC_DIR)/completions
COMPLETIONS_EXTENDED_SRC ?= $(SRC_DIR)/completions-extended
PACKAGES_DIR ?= $(SRC_DIR)/packages
BIN_SRC ?= $(SRC_DIR)/usr/local/bin
DISTRO_FILES_SRC ?= $(SRC_DIR)/distro-files
PROFILE_D_SRC ?= $(SRC_DIR)/profile.d
PROFILE_D_DEST ?= $(ETC_DIR)/profile.d
SKEL_DEST ?= $(ETC_DIR)/skel
DOCKER_MODE ?= no
EXTENDED_COMPLETIONS ?= no
EXTENDED_HOME_FILES ?= no
# Allow ROOT=1 to override INSTALL_USER (even if set in config.mk)
ifeq ($(ROOT),1)
override INSTALL_USER := root
else
INSTALL_USER ?= $(shell whoami)
endif
GROUP_NAME ?= cognitify
VERSION ?= 0.0.1

# Colours for output
RED := \033[0;31m
GREEN := \033[0;32m
YELLOW := \033[0;33m
NC := \033[0m # No Colour

.PHONY: help all install install-root install-all install-config install-prompts install-completions install-home install-bin install-docs install-man install-distro install-profile-d install-skel post-install clean uninstall check-root

help: ## Show this help message
	@echo "Cognitify Build System"
	@echo ""
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*?## "}; /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-20s$(NC) %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@echo ""
	@echo "Configuration (from config.mk):"
	@echo "  Distribution: $(DISTRO_ID)"
	@echo "  Package Manager: $(PKG_MANAGER)"
	@echo "  Prefix: $(PREFIX)"
	@echo "  Config Dest: $(CONFIG_DEST)"
	@echo "  Install User: $(INSTALL_USER)"

all: ## Build the project (currently just validates)
	@echo "$(GREEN)[cognitify]$(NC) Building..."
	@if [ ! -d "$(SRC_DIR)" ]; then \
		echo "$(RED)Error: Source directory not found: $(SRC_DIR)$(NC)" >&2; \
		exit 1; \
	fi
	@if [ ! -f "version" ]; then \
		echo "$(YELLOW)Warning: version file not found$(NC)" >&2; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Build validation complete"

check-root: ## Check if running as root (for install targets)
	@if [ "$$(id -u)" -ne 0 ]; then \
		echo "$(RED)Error: This target requires root privileges. Use: sudo make install$(NC)" >&2; \
		exit 1; \
	fi

install: check-root all install-config install-prompts install-completions install-home install-bin install-distro install-docs install-man install-profile-d install-skel post-install ## Install all components
	@echo ""
	@echo "$(GREEN)[cognitify]$(NC) Installation completed successfully!"
	@echo "$(GREEN)[cognitify]$(NC) Version $(VERSION) installed"
	@if [ "$(ALL)" = "1" ]; then \
		echo "$(GREEN)[cognitify]$(NC) Installed for all users"; \
	else \
		echo "$(GREEN)[cognitify]$(NC) Installed for user: $(INSTALL_USER)"; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Please log out and log back in for changes to take effect"

install-root: ## Install for root user (alias for: make install ROOT=1)
	$(MAKE) install ROOT=1

install-all: ## Install for all users (requires root, alias for: make install ALL=1)
	$(MAKE) install ALL=1

install-config: check-root ## Install bash configuration files
	@echo "$(GREEN)[cognitify]$(NC) Installing configuration files..."
	@if [ ! -d "$(CONFIG_SRC)" ]; then \
		echo "$(RED)Error: Configuration source not found: $(CONFIG_SRC)$(NC)" >&2; \
		exit 1; \
	fi
	@install -d -m 775 -o root -g "$(GROUP_NAME)" "$(CONFIG_DEST)" || \
		(if ! getent group "$(GROUP_NAME)" >/dev/null 2>&1; then \
			echo "$(GREEN)[cognitify]$(NC) Creating group $(GROUP_NAME)..."; \
			groupadd "$(GROUP_NAME)"; \
		fi; \
		install -d -m 775 -o root -g "$(GROUP_NAME)" "$(CONFIG_DEST)")
	@cp -R "$(CONFIG_SRC)/." "$(CONFIG_DEST)/"
	@chown -R root:"$(GROUP_NAME)" "$(CONFIG_DEST)"
	@chmod -R 775 "$(CONFIG_DEST)"
	@echo "$(CONFIG_DEST)/.cognitify-version" | xargs -I {} sh -c 'echo "$(VERSION)" > {}'
	@chmod 644 "$(CONFIG_DEST)/.cognitify-version"
	@echo "$(GREEN)[cognitify]$(NC) Configuration installed to $(CONFIG_DEST)"

install-prompts: check-root ## Install prompt configuration files
	@echo "$(GREEN)[cognitify]$(NC) Installing prompt files..."
	@if [ ! -d "$(PROMPTS_SRC)" ]; then \
		echo "$(YELLOW)Warning: Prompts source not found: $(PROMPTS_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 775 -o root -g "$(GROUP_NAME)" "$(PROMPTS_DEST)" || \
		(if ! getent group "$(GROUP_NAME)" >/dev/null 2>&1; then \
			echo "$(GREEN)[cognitify]$(NC) Creating group $(GROUP_NAME)..."; \
			groupadd "$(GROUP_NAME)"; \
		fi; \
		install -d -m 775 -o root -g "$(GROUP_NAME)" "$(PROMPTS_DEST)")
	@if [ -d "$(PROMPTS_SRC)/lib" ]; then \
		install -d -m 775 -o root -g "$(GROUP_NAME)" "$(PROMPTS_DEST)/lib"; \
		cp -R "$(PROMPTS_SRC)/lib/." "$(PROMPTS_DEST)/lib/"; \
		chown -R root:"$(GROUP_NAME)" "$(PROMPTS_DEST)/lib"; \
		chmod -R 775 "$(PROMPTS_DEST)/lib"; \
	fi
	@for file in "$(PROMPTS_SRC)"/*; do \
		[ -f "$$file" ] || continue; \
		install -m 644 "$$file" "$(PROMPTS_DEST)/"; \
		chown root:"$(GROUP_NAME)" "$(PROMPTS_DEST)/$$(basename "$$file")"; \
	done
	@echo "$(PROMPTS_DEST)/.cognitify-version" | xargs -I {} sh -c 'echo "$(VERSION)" > {}'
	@chmod 644 "$(PROMPTS_DEST)/.cognitify-version"
	@echo "$(GREEN)[cognitify]$(NC) Prompts installed to $(PROMPTS_DEST)"

install-completions: check-root ## Install shell completions
	@echo "$(GREEN)[cognitify]$(NC) Installing shell completions..."
	@if [ ! -d "$(COMPLETIONS_SRC)" ]; then \
		echo "$(YELLOW)Warning: Completions source not found: $(COMPLETIONS_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@if [ -z "$$(find "$(COMPLETIONS_SRC)" -maxdepth 1 -type f 2>/dev/null)" ]; then \
		echo "$(YELLOW)Warning: No completion files found in $(COMPLETIONS_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(COMPLETIONS_DEST)"
	@for file in "$(COMPLETIONS_SRC)"/*; do \
		[ -f "$$file" ] || continue; \
		install -m 644 "$$file" "$(COMPLETIONS_DEST)/"; \
		echo "$(GREEN)[cognitify]$(NC) Installed completion: $$(basename "$$file")"; \
	done
	@echo "$(GREEN)[cognitify]$(NC) Completions installed to $(COMPLETIONS_DEST)"

install-home: check-root ## Install user dotfiles
	@if [ "$(ALL)" = "1" ]; then \
		echo "$(GREEN)[cognitify]$(NC) Installing home directory files for all users..."; \
		if [ ! -d "$(HOME_FILES_SRC)" ]; then \
			echo "$(YELLOW)Warning: Home files source not found: $(HOME_FILES_SRC)$(NC)" >&2; \
			exit 0; \
		fi; \
		USER_COUNT=0; \
		FAILED_COUNT=0; \
		while IFS=: read -r username _ uid gid _ home_dir shell; do \
			if [ -z "$$username" ] || [ -z "$$home_dir" ]; then \
				continue; \
			fi; \
			if [ "$$uid" -lt 1000 ] && [ "$$username" != "root" ]; then \
				continue; \
			fi; \
			if [ ! -d "$$home_dir" ]; then \
				continue; \
			fi; \
			if [ "$$shell" = "/usr/sbin/nologin" ] || [ "$$shell" = "/sbin/nologin" ] || [ "$$shell" = "/bin/false" ]; then \
				continue; \
			fi; \
			USER_COUNT=$$((USER_COUNT + 1)); \
			echo "$(GREEN)[cognitify]$(NC) Installing for user: $$username ($$home_dir)"; \
			USER_GROUP=$$(getent group "$$gid" | cut -d: -f1 2>/dev/null || echo "$$username"); \
			USER_FAILED=0; \
			for file in "$(HOME_FILES_SRC)"/*; do \
				[ -f "$$file" ] || continue; \
				base=".$$(basename "$$file")"; \
				dest="$$home_dir/$$base"; \
				if [ -e "$$dest" ] && [ ! -e "$$dest.orig" ]; then \
					if ! cp "$$dest" "$$dest.orig" 2>/dev/null; then \
						echo "$(YELLOW)Warning: Failed to backup $$base for user $$username$(NC)" >&2; \
					fi; \
				fi; \
				if ! cp "$$file" "$$dest" 2>/dev/null; then \
					echo "$(RED)Error: Failed to copy $$base to $$home_dir for user $$username$(NC)" >&2; \
					USER_FAILED=1; \
					continue; \
				fi; \
				if ! chown "$$username:$$USER_GROUP" "$$dest" 2>/dev/null && ! chown "$$username" "$$dest" 2>/dev/null; then \
					echo "$(YELLOW)Warning: Failed to set ownership for $$base for user $$username$(NC)" >&2; \
				fi; \
			done; \
			if [ "$(EXTENDED_HOME_FILES)" = "yes" ] && [ -d "$(HOME_FILES_EXTENDED_SRC)" ]; then \
				for file in "$(HOME_FILES_EXTENDED_SRC)"/*; do \
					[ -f "$$file" ] || continue; \
					base=".$$(basename "$$file")"; \
					dest="$$home_dir/$$base"; \
					if [ -e "$$dest" ] && [ ! -e "$$dest.orig" ]; then \
						if ! cp "$$dest" "$$dest.orig" 2>/dev/null; then \
							echo "$(YELLOW)Warning: Failed to backup $$base for user $$username$(NC)" >&2; \
						fi; \
					fi; \
					if ! cp "$$file" "$$dest" 2>/dev/null; then \
						echo "$(RED)Error: Failed to copy $$base to $$home_dir for user $$username$(NC)" >&2; \
						USER_FAILED=1; \
						continue; \
					fi; \
					if ! chown "$$username:$$USER_GROUP" "$$dest" 2>/dev/null && ! chown "$$username" "$$dest" 2>/dev/null; then \
						echo "$(YELLOW)Warning: Failed to set ownership for $$base for user $$username$(NC)" >&2; \
					fi; \
				done; \
			fi; \
			if [ "$$USER_FAILED" -eq 1 ]; then \
				FAILED_COUNT=$$((FAILED_COUNT + 1)); \
			fi; \
		done < /etc/passwd; \
		if [ "$$USER_COUNT" -eq 0 ]; then \
			echo "$(YELLOW)Warning: No users found to install dotfiles for$(NC)" >&2; \
		else \
			if [ "$$FAILED_COUNT" -eq 0 ]; then \
				echo "$(GREEN)[cognitify]$(NC) Home files installed successfully for $$USER_COUNT user(s)"; \
			else \
				echo "$(YELLOW)[cognitify]$(NC) Home files installed for $$USER_COUNT user(s) with $$FAILED_COUNT failure(s)"; \
			fi; \
		fi; \
	else \
		echo "$(GREEN)[cognitify]$(NC) Installing home directory files for user: $(INSTALL_USER)..."; \
		HOME_DIR=$$(getent passwd "$(INSTALL_USER)" | cut -d: -f6); \
		if [ -z "$$HOME_DIR" ]; then \
			if [ "$(INSTALL_USER)" = "root" ]; then \
				HOME_DIR="/root"; \
			else \
				echo "$(RED)Error: Unable to resolve home directory for user $(INSTALL_USER)$(NC)" >&2; \
				exit 1; \
			fi; \
		fi; \
		if [ ! -d "$$HOME_DIR" ]; then \
			echo "$(RED)Error: Home directory does not exist: $$HOME_DIR$(NC)" >&2; \
			exit 1; \
		fi; \
		USER_GROUP=$$(id -gn "$(INSTALL_USER)" 2>/dev/null || echo "$(INSTALL_USER)"); \
		if [ ! -d "$(HOME_FILES_SRC)" ]; then \
			echo "$(YELLOW)Warning: Home files source not found: $(HOME_FILES_SRC)$(NC)" >&2; \
			exit 0; \
		fi; \
		for file in "$(HOME_FILES_SRC)"/*; do \
			[ -f "$$file" ] || continue; \
			base=".$$(basename "$$file")"; \
			dest="$$HOME_DIR/$$base"; \
			if [ -e "$$dest" ] && [ ! -e "$$dest.orig" ]; then \
				cp "$$dest" "$$dest.orig"; \
				echo "$(GREEN)[cognitify]$(NC) Backed up existing $$base to $$base.orig"; \
			fi; \
			cp "$$file" "$$dest"; \
			chown "$(INSTALL_USER):$$USER_GROUP" "$$dest" 2>/dev/null || chown "$(INSTALL_USER)" "$$dest"; \
		done; \
		echo "$(GREEN)[cognitify]$(NC) Home files installed to $$HOME_DIR"; \
	fi

install-bin: check-root ## Install user binaries
	@echo "$(GREEN)[cognitify]$(NC) Installing user binaries..."
	@if [ ! -d "$(BIN_SRC)" ]; then \
		echo "$(YELLOW)Warning: Binaries source not found: $(BIN_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(PREFIX)/bin"
	@for file in "$(BIN_SRC)"/*; do \
		[ -f "$$file" ] && [ -x "$$file" ] || continue; \
		install -m 755 "$$file" "$(PREFIX)/bin/"; \
	done
	@echo "$(GREEN)[cognitify]$(NC) Binaries installed to $(PREFIX)/bin"

install-docs: check-root ## Install documentation
	@echo "$(GREEN)[cognitify]$(NC) Installing documentation..."
	@if [ ! -d "docs" ]; then \
		echo "$(YELLOW)Warning: Documentation directory not found$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(PREFIX)/share/doc/cognitify"
	@cp -r docs/* "$(PREFIX)/share/doc/cognitify/" 2>/dev/null || true
	@find "$(PREFIX)/share/doc/cognitify" -type f -exec chmod 644 {} \;
	@find "$(PREFIX)/share/doc/cognitify" -type d -exec chmod 755 {} \;
	@echo "$(GREEN)[cognitify]$(NC) Documentation installed to $(PREFIX)/share/doc/cognitify"

install-man: check-root ## Install man page
	@echo "$(GREEN)[cognitify]$(NC) Installing man page..."
	@if [ ! -f "man/man1/cognitify.1" ]; then \
		echo "$(YELLOW)Warning: Man page not found$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(PREFIX)/share/man/man1"
	@install -m 644 "man/man1/cognitify.1" "$(PREFIX)/share/man/man1/"
	@if command -v mandb >/dev/null 2>&1; then \
		mandb -q >/dev/null 2>&1 || true; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Man page installed to $(PREFIX)/share/man/man1"

install-distro: check-root ## Install distro-specific files
	@echo "$(GREEN)[cognitify]$(NC) Installing distro-specific files..."
	@if [ ! -d "$(DISTRO_FILES_SRC)" ]; then \
		echo "$(YELLOW)Warning: Distro files source not found: $(DISTRO_FILES_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@case "$(PKG_MANAGER)" in \
		zypper) \
			if [ -f "$(DISTRO_FILES_SRC)/zypper.sh" ]; then \
				install -m 644 "$(DISTRO_FILES_SRC)/zypper.sh" "$(COMPLETIONS_DEST)/zypper" || true; \
				echo "$(GREEN)[cognitify]$(NC) Installed zypper completion"; \
			fi \
			;; \
	esac

install-profile-d: check-root ## Install system-wide profile.d snippet
	@echo "$(GREEN)[cognitify]$(NC) Installing profile.d snippet..."
	@if [ ! -d "$(PROFILE_D_SRC)" ]; then \
		echo "$(YELLOW)Warning: Profile.d source not found: $(PROFILE_D_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(PROFILE_D_DEST)"
	@for file in "$(PROFILE_D_SRC)"/*; do \
		[ -f "$$file" ] || continue; \
		install -m 644 "$$file" "$(PROFILE_D_DEST)/"; \
		echo "$(GREEN)[cognitify]$(NC) Installed $$(basename "$$file") to $(PROFILE_D_DEST)"; \
	done
	@echo "$(GREEN)[cognitify]$(NC) Profile.d snippet installed to $(PROFILE_D_DEST)"

install-skel: check-root ## Install dotfiles to /etc/skel for new users
	@echo "$(GREEN)[cognitify]$(NC) Installing dotfiles to /etc/skel..."
	@if [ ! -d "$(HOME_FILES_SRC)" ]; then \
		echo "$(YELLOW)Warning: Home files source not found: $(HOME_FILES_SRC)$(NC)" >&2; \
		exit 0; \
	fi
	@install -d -m 755 "$(SKEL_DEST)"
	@for file in "$(HOME_FILES_SRC)"/*; do \
		[ -f "$$file" ] || continue; \
		base=".$$(basename "$$file")"; \
		dest="$(SKEL_DEST)/$$base"; \
		install -m 644 "$$file" "$$dest"; \
		echo "$(GREEN)[cognitify]$(NC) Installed $$base to $(SKEL_DEST)"; \
	done
	@echo "$(GREEN)[cognitify]$(NC) Dotfiles installed to $(SKEL_DEST)"

post-install: check-root ## Run post-installation script (package installation)
	@if [ "$(SKIP_PACKAGES)" = "yes" ]; then \
		echo "$(GREEN)[cognitify]$(NC) Skipping package installation (SKIP_PACKAGES=yes)"; \
		exit 0; \
	fi
	@if [ "$(PKG_MANAGER)" = "unknown" ] || [ -z "$(PKG_MANAGER)" ]; then \
		echo "$(YELLOW)Warning: No supported package manager detected. Skipping package installation.$(NC)" >&2; \
		exit 0; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Running post-installation package script..."
	@./post-install.sh "$(PKG_MANAGER)" "$(PKG_MANAGER_INSTALL)" "$(PKG_MANAGER_UPDATE)" "$(PACKAGES_DIR)" "no" "$(DOCKER_MODE)"

clean: ## Clean build artifacts
	@echo "$(GREEN)[cognitify]$(NC) Cleaning..."
	@rm -f config.mk
	@echo "$(GREEN)[cognitify]$(NC) Clean complete"

uninstall: check-root ## Uninstall cognitify (removes files but keeps backups)
	@echo "$(RED)[cognitify]$(NC) Uninstalling..."
	@echo "$(YELLOW)Warning: This will remove installed files but keep backups with .orig suffix$(NC)"
	@read -p "Continue? [y/N] " -n 1 -r; \
	echo; \
	if [[ ! $$REPLY =~ ^[Yy]$$ ]]; then \
		echo "Cancelled."; \
		exit 0; \
	fi
	@rm -rf "$(CONFIG_DEST)"
	@rm -rf "$(PROMPTS_DEST)" 2>/dev/null || true
	@rm -rf "$(COMPLETIONS_DEST)"/*cognitify* 2>/dev/null || true
	@HOME_DIR=$$(getent passwd "$(INSTALL_USER)" | cut -d: -f6); \
	if [ -n "$$HOME_DIR" ] && [ -d "$$HOME_DIR" ]; then \
		for file in "$(HOME_FILES_SRC)"/*; do \
			[ -f "$$file" ] || continue; \
			base=".$$(basename "$$file")"; \
			dest="$$HOME_DIR/$$base"; \
			if [ -e "$$dest" ]; then \
				rm -f "$$dest"; \
				if [ -e "$$dest.orig" ]; then \
					mv "$$dest.orig" "$$dest"; \
					echo "$(GREEN)[cognitify]$(NC) Restored $$base from backup"; \
				fi; \
			fi; \
		done; \
	fi
	@echo "$(GREEN)[cognitify]$(NC) Uninstall complete"
