## (c) 2026
## Ramon Brooker <rbrooker@aeo3.io>

# ~/.bash_logout: executed by bash(1) when login shell exits.
# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

echo "logged out at $(date) by $(whoami)" >> "${HOME}/.bash_logout.log" 2>&1

exit 0
