#!/bin/bash

export DIRS_FUNCTION_VERSION=1

## (C) 2023
## Ramon Brooker <rbrooker@aeo3.io>

function list-empty-dirs() {
    find . -type d -empty -print
}

function del-empty-dirs() {
    #	if [[ ${PWD} = ${HOME} ]]; then
    #		echo "Are you sure you want to delete these files? "
    #	promtp
    #	fi
    find . -type d -empty -delete
}
